import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../feeds/presentation/feed_controller.dart';

class ChatScreen extends ConsumerStatefulWidget { const ChatScreen({super.key, required this.userId, required this.name}); final int userId; final String name; @override ConsumerState<ChatScreen> createState() => _ChatScreenState(); }
class _ChatScreenState extends ConsumerState<ChatScreen> {
  final _text = TextEditingController(); final _scroll = ScrollController(); List<Map<String, dynamic>> _messages = []; var _loading = true; var _sending = false;
  @override void initState() { super.initState(); _load(); }
  @override void dispose() { _text.dispose(); _scroll.dispose(); super.dispose(); }
  Future<void> _load() async { try { final result = await ref.read(apiProvider).get('/api/messages/${widget.userId}'); final list = result['data'] as List<dynamic>? ?? const []; if (mounted) setState(() => _messages = list.cast<Map<String, dynamic>>()); await ref.read(apiProvider).put('/api/messages/read/${widget.userId}'); } catch (_) { if (mounted) _notice('Unable to load this conversation.'); } finally { if (mounted) setState(() => _loading = false); } }
  Future<void> _send() async { final value = _text.text.trim(); if (value.isEmpty || _sending) return; setState(() => _sending = true); try { final result = await ref.read(apiProvider).post('/api/messages/send', data: {'receiver_id': widget.userId, 'message': value}); final data = result['data'] as Map<String, dynamic>; if (mounted) setState(() { _messages = [..._messages, data]; _text.clear(); }); } catch (_) { _notice("Message couldn't be sent. Please try again."); } finally { if (mounted) setState(() => _sending = false); } }
  void _notice(String text) => ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(text)));
  @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(widget.name), Text('Messages are private', style: Theme.of(context).textTheme.labelSmall)])), body: Column(children: [Expanded(child: _loading ? const Center(child: CircularProgressIndicator()) : ListView.builder(controller: _scroll, padding: const EdgeInsets.all(16), itemCount: _messages.length, itemBuilder: (_, index) { final message = _messages[index]; final mine = message['sender_id'] != widget.userId; return Align(alignment: mine ? Alignment.centerRight : Alignment.centerLeft, child: Container(margin: const EdgeInsets.only(bottom: 8), padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10), decoration: BoxDecoration(color: mine ? Theme.of(context).colorScheme.primary : Theme.of(context).colorScheme.surfaceContainerHighest, borderRadius: BorderRadius.circular(18)), child: Text(message['message'] as String? ?? '', style: TextStyle(color: mine ? Theme.of(context).colorScheme.onPrimary : null)))); })), SafeArea(top: false, child: Padding(padding: const EdgeInsets.fromLTRB(12, 6, 12, 12), child: Row(children: [Expanded(child: TextField(controller: _text, textCapitalization: TextCapitalization.sentences, onSubmitted: (_) => _send(), decoration: const InputDecoration(hintText: 'Write a message…', border: OutlineInputBorder()))), const SizedBox(width: 8), IconButton.filled(onPressed: _sending ? null : _send, icon: const Icon(Icons.send), tooltip: 'Send')])))]));
}
