import { useEffect, useState } from "react";
import { HiOutlineBriefcase, HiOutlineCamera, HiOutlineGlobeAlt, HiOutlineLocationMarker, HiOutlineOfficeBuilding, HiOutlinePencil, HiOutlineSave, HiOutlineUser } from "react-icons/hi";
import { useNavigate } from "react-router-dom";
import toast from "react-hot-toast";
import api from "../../services/apiClient";
import BackButton from "../../components/BackButton";
import { useAuth } from "../../context/AuthContext";

const blank = { name: "", username: "", description: "", location: "", occupation: "", company: "", website: "", phone_number: "" };
export default function EditProfile() {
  const navigate = useNavigate(), { setUser } = useAuth();
  const [form, setForm] = useState(blank), [picture, setPicture] = useState(null), [preview, setPreview] = useState("/default-profile.png"), [status, setStatus] = useState(""), [saving, setSaving] = useState(false);
  useEffect(() => { api.get("/api/current_user").then(({ data }) => { setForm(Object.fromEntries(Object.keys(blank).map(key => [key, data[key] || ""]))); setPreview(data.picture || "/default-profile.png"); }).catch(() => setStatus("We could not load your profile.")); }, []);
  const update = (key, value) => setForm(current => ({ ...current, [key]: value }));
  const choosePicture = (event) => { const file = event.target.files?.[0]; if (!file) return; if (!file.type.startsWith("image/") || file.size > 20 * 1024 * 1024) { toast.error("Choose an image smaller than 20 MB."); return; } setPicture(file); setPreview(URL.createObjectURL(file)); };
  const submit = async (event) => { event.preventDefault(); setSaving(true); setStatus(""); try { const data = new FormData(); Object.entries(form).forEach(([key, value]) => data.append(key, value.trim())); if (picture) data.append("picture", picture); await api.post("/api/profile", data); const { data: refreshed } = await api.get("/api/current_user"); setUser(refreshed); toast.success("Profile updated successfully."); navigate("/profile"); } catch (error) { setStatus(error.response?.data?.error || error.response?.data?.message || "Your changes could not be saved."); } finally { setSaving(false); } };
  return <section className="workspace-page edit-profile-page"><BackButton fallback="/profile" label="Back to profile" /><form className="surface-card profile-form" onSubmit={submit}><header className="profile-form__header"><label className="profile-photo-picker"><img src={preview} alt="Profile preview" /><span><HiOutlineCamera /></span><input type="file" accept="image/*" onChange={choosePicture} /></label><div><p className="eyebrow">YOUR PROFILE</p><h1>Edit profile</h1><p>Choose the information you want your community to see.</p></div></header>{status && <p className="form-error">{status}</p>}<div className="profile-form__fields profile-form__fields--grid"><label><span><HiOutlineUser /> Name</span><input required value={form.name} onChange={event => update("name", event.target.value)} placeholder="Your name" /></label><label><span><HiOutlineUser /> Username</span><input value={form.username} onChange={event => update("username", event.target.value)} placeholder="Your public username" /></label><label className="profile-field-wide"><span><HiOutlinePencil /> Bio</span><textarea maxLength="500" value={form.description} onChange={event => update("description", event.target.value)} placeholder="Tell people a little about yourself" rows="4" /></label><label><span><HiOutlineLocationMarker /> Location</span><input value={form.location} onChange={event => update("location", event.target.value)} placeholder="Where are you based?" /></label><label><span><HiOutlineBriefcase /> Occupation</span><input value={form.occupation} onChange={event => update("occupation", event.target.value)} placeholder="What do you do?" /></label><label><span><HiOutlineOfficeBuilding /> Company</span><input value={form.company} onChange={event => update("company", event.target.value)} placeholder="Company or organisation" /></label><label><span><HiOutlineGlobeAlt /> Website</span><input type="url" value={form.website} onChange={event => update("website", event.target.value)} placeholder="https://example.com" /></label><label className="profile-field-wide"><span>Phone number</span><input type="tel" value={form.phone_number} onChange={event => update("phone_number", event.target.value)} placeholder="Optional contact number" /></label></div><footer className="profile-form__actions"><button type="button" className="button-secondary" onClick={() => navigate("/profile")}>Cancel</button><button className="button-primary" disabled={saving}><HiOutlineSave /> {saving ? "Saving…" : "Save changes"}</button></footer></form></section>;
}
