import { useState } from "react";
import { GoogleAuthProvider, signInWithPopup } from "firebase/auth";
import { HiEye, HiEyeOff, HiLockClosed, HiMail } from "react-icons/hi";
import { Link, useLocation, useNavigate } from "react-router-dom";
import toast from "react-hot-toast";
import { useAuth } from "../context/AuthContext";
import { firebaseAuth } from "../services/firebase";
import api from "../services/apiClient";
export default function LoginPage() {
  const [form, setForm] = useState({ email: "", password: "", remember: true }); const [showPassword, setShowPassword] = useState(false); const [submitting, setSubmitting] = useState(false);
  const { loadSession } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const destination = location.state?.from?.pathname || "/home";
  const finish = async () => { await loadSession(); navigate(destination, { replace: true }); };
  const submit = async event => { event.preventDefault(); setSubmitting(true); try { await api.post("/api/login", { email: form.email, password: form.password }); toast.success("Welcome back."); await finish(); } catch (error) { toast.error(error.response?.data?.message || "We couldn’t sign you in."); } finally { setSubmitting(false); } };
  const google = async () => { setSubmitting(true); try { const result = await signInWithPopup(firebaseAuth, new GoogleAuthProvider()); await api.post("/api/google-login", { id_token: await result.user.getIdToken() }); await finish(); } catch (error) { toast.error(error.response?.data?.message || "Google sign-in did not complete."); } finally { setSubmitting(false); } };
  return <section className="auth-card"><Link to="/" className="brand auth-brand"><span>✦</span>desire</Link><div className="auth-heading"><p className="eyebrow">WELCOME BACK</p><h1>Pick up where you left off.</h1><p>Sign in to your quieter social space.</p></div><form onSubmit={submit}><label>Email address<span className="input-wrap"><HiMail /><input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} placeholder="you@example.com" /></span></label><label>Password<span className="input-wrap"><HiLockClosed /><input required type={showPassword ? "text" : "password"} value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} placeholder="Your password" /><button type="button" className="password-toggle" onClick={() => setShowPassword(v => !v)}>{showPassword ? <HiEyeOff /> : <HiEye />}</button></span></label><div className="form-options"><label className="checkbox"><input type="checkbox" checked={form.remember} onChange={e => setForm({ ...form, remember: e.target.checked })} /> Remember me</label><button type="button" className="text-link">Forgot password?</button></div><button className="primary-link form-submit" disabled={submitting}>{submitting ? "Signing in…" : "Sign in"}</button></form><div className="divider"><span>or continue with</span></div><div className="oauth-actions"><button onClick={google} disabled={submitting}>Google</button><button onClick={() => { window.location.assign(`${import.meta.env.VITE_API_BASE_URL}/api/github-login`); }} disabled={submitting}>GitHub</button></div><p className="auth-footer">New here? <Link to="/signup">Create an account</Link></p></section>;
}
