import { useEffect, useState } from "react";
import { HiOutlineAdjustments, HiOutlineBell, HiOutlineColorSwatch, HiOutlineInformationCircle, HiOutlineKey, HiOutlineLockClosed, HiOutlineOfficeBuilding, HiOutlineUser, HiOutlineUserGroup } from "react-icons/hi";
import { useTheme } from "../context/ThemeContext";
import { Link, useNavigate } from "react-router-dom";
import toast from "react-hot-toast";
import api from "../services/apiClient";
import { useAuth } from "../context/AuthContext";

const groups = [
  ["general", "General", HiOutlineAdjustments], ["profile", "Profile", HiOutlineUser], ["business", "Business", HiOutlineOfficeBuilding], ["appearance", "Appearance", HiOutlineColorSwatch], ["notifications", "Notifications", HiOutlineBell], ["security", "Security", HiOutlineLockClosed], ["api", "API Keys", HiOutlineKey], ["accounts", "Connected Accounts", HiOutlineUserGroup], ["users", "Users & roles", HiOutlineUserGroup], ["billing", "Billing", HiOutlineOfficeBuilding], ["integrations", "Integrations", HiOutlineAdjustments], ["backup", "Backup", HiOutlineLockClosed], ["about", "About", HiOutlineInformationCircle],
];
const ComingSoon = ({ title, copy }) => <div className="settings-section"><h2>{title}</h2><p>{copy}</p><div className="settings-placeholder">This workspace setting is ready for your organisation’s configuration.</div></div>;
export default function SettingsPage() {
  const [active, setActive] = useState("general"); const { theme, setTheme } = useTheme(); const navigate = useNavigate(); const { user, setUser } = useAuth();
  const [preferences, setPreferences] = useState({ email: true, push: false, mentions: true });
  useEffect(() => { if (user?.settings?.notifications) setPreferences(current => ({ ...current, ...user.settings.notifications })); }, [user]);
  const saveProfilePreference = async (fields) => { const payload = new FormData(); Object.entries(fields).forEach(([key, value]) => payload.append(key, typeof value === "string" ? value : JSON.stringify(value))); const { data } = await api.post("/api/profile", payload); const current = await api.get("/api/current_user"); setUser(current.data); return data; };
  const chooseTheme = async (value) => { setTheme(value); try { await saveProfilePreference({ theme_preference: value }); toast.success("Appearance preference saved."); } catch { toast.error("Appearance changed locally but could not be saved."); } };
  const togglePreference = async (key) => { const next = { ...preferences, [key]: !preferences[key] }; setPreferences(next); try { await saveProfilePreference({ settings: { notifications: next } }); } catch { setPreferences(preferences); toast.error("Notification preference could not be saved."); } };
  const deleteAccount = async () => { if (!window.confirm("Are you sure you want to delete your account? This cannot be undone from the app.")) return; try { await api.delete("/api/account", { data: { confirm: true } }); toast.success("Your account has been deleted."); navigate("/"); } catch (error) { toast.error(error.response?.data?.message || "Your account could not be deleted. Please try again."); } };
  const content = active === "profile" ? <div className="settings-section"><h2>Profile</h2><p>Manage the information people see when they visit your profile.</p><div className="settings-profile-summary"><img src={user?.picture || "/default-profile.png"} alt="" /><div><strong>{user?.name || "Your profile"}</strong><small>{user?.username ? `@${user.username}` : "Add a username to make your profile easier to find."}</small></div><Link className="button-primary" to="/edit-profile">Edit profile</Link></div></div> : active === "appearance" ? <div className="settings-section"><h2>Appearance</h2><p>Choose how Mbogi looks on this device.</p><div className="choice-grid">{[["light", "Light"], ["dark", "Dark"], ["system", "System"]].map(([value, label]) => <button className={`theme-choice ${theme === value ? "selected" : ""}`} onClick={() => chooseTheme(value)} key={value}><span className={`theme-preview ${value}`} /><strong>{label}</strong><small>{value === "system" ? "Match your device" : `${label} theme`}</small></button>)}</div></div> : active === "notifications" ? <div className="settings-section"><h2>Notification preferences</h2><p>Control the updates you receive.</p>{Object.entries(preferences).map(([key, value]) => <label className="preference-row" key={key}><span><strong>{key === "email" ? "Email updates" : key === "push" ? "Push notifications" : "Mentions and replies"}</strong><small>Receive timely activity updates.</small></span><input type="checkbox" checked={value} onChange={() => togglePreference(key)} /></label>)}</div> : active === "security" ? <div className="settings-section"><h2>Security</h2><p>Manage access to your account.</p><div className="danger-zone"><strong>Delete account</strong><p>Deletes your profile from the app and signs you out.</p><button className="button-danger" onClick={deleteAccount}>Delete my account</button></div></div> : <ComingSoon title={groups.find(g => g[0] === active)?.[1]} copy={active === "general" ? "Manage workspace preferences and defaults." : "Configure this area without leaving your workspace."} />;
  return <section className="workspace-page settings-page"><header className="page-heading"><div><p className="eyebrow">PREFERENCES</p><h1>Settings</h1><p>Manage your account, experience, and workspace controls.</p></div></header><div className="settings-layout"><nav className="settings-nav" aria-label="Settings sections">{groups.map(([id,label,Icon]) => <button key={id} onClick={() => setActive(id)} className={active === id ? "active" : ""}><Icon />{label}</button>)}</nav><div className="surface-card settings-content">{content}</div></div></section>;
}
