import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'feed_controller.dart';

class CommentsSheet extends ConsumerStatefulWidget { const CommentsSheet({super.key, required this.postId}); final int postId; @override ConsumerState<CommentsSheet> createState() => _CommentsSheetState(); }
class _CommentsSheetState extends ConsumerState<CommentsSheet> { final _text = TextEditingController(); List<Map<String, dynamic>> _comments = []; var _loading = true; var _sending = false;
  @override void initState() { super.initState(); _load(); }
  @override void dispose() { _text.dispose(); super.dispose(); }
  Future<void> _load() async { try { final result = await ref.read(apiProvider).get('/api/posts/${widget.postId}/comments'); final data = result['data'] as List<dynamic>? ?? const []; if (mounted) setState(() => _comments = data.cast<Map<String, dynamic>>()); } finally { if (mounted) setState(() => _loading = false); } }
  Future<void> _send() async { final content = _text.text.trim(); if (content.isEmpty || _sending) return; setState(() => _sending = true); try { final result = await ref.read(apiProvider).post('/api/posts/${widget.postId}/comments', data: {'content': content}); if (mounted) setState(() { _comments = [..._comments, result['data'] as Map<String, dynamic>]; _text.clear(); }); } catch (_) { _notice('Your comment could not be posted.'); } finally { if (mounted) setState(() => _sending = false); } }
  Future<void> _delete(Map<String, dynamic> comment) async { try { await ref.read(apiProvider).delete('/api/comments/${comment['id']}'); if (mounted) setState(() => _comments = _comments.where((item) => item['id'] != comment['id']).toList()); } catch (_) { _notice('Could not delete this comment.'); } }
  void _notice(String text) => ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(text)));
  @override Widget build(BuildContext context) => SafeArea(child: Padding(padding: EdgeInsets.only(bottom: MediaQuery.of(context).viewInsets.bottom), child: SizedBox(height: MediaQuery.of(context).size.height * .72, child: Column(children: [const SizedBox(height: 12), Container(width: 40, height: 4, decoration: BoxDecoration(color: Theme.of(context).colorScheme.outlineVariant, borderRadius: BorderRadius.circular(8))), const SizedBox(height: 12), Text('Comments', style: Theme.of(context).textTheme.titleLarge), Expanded(child: _loading ? const Center(child: CircularProgressIndicator()) : _comments.isEmpty ? const Center(child: Text('Be the first to comment.')) : ListView.builder(itemCount: _comments.length, itemBuilder: (_, index) { final comment = _comments[index]; final photo = comment['user_photo'] as String?; final userId = comment['user_id']; return ListTile(leading: GestureDetector(onTap: userId == null ? null : () => context.push('/profile/$userId'), child: CircleAvatar(backgroundImage: photo == null ? null : CachedNetworkImageProvider(photo), child: photo == null ? Text((comment['user_name'] as String? ?? 'U').substring(0, 1)) : null)), title: Text(comment['user_name'] as String? ?? 'User'), subtitle: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(comment['content'] as String? ?? ''), Text(_time(comment['timestamp'] as String?), style: Theme.of(context).textTheme.labelSmall)]), trailing: comment['is_owner'] == true ? IconButton(onPressed: () => _delete(comment), icon: const Icon(Icons.delete_outline), tooltip: 'Delete comment') : null); })), Padding(padding: const EdgeInsets.all(12), child: Row(children: [Expanded(child: TextField(controller: _text, textCapitalization: TextCapitalization.sentences, onSubmitted: (_) => _send(), decoration: const InputDecoration(hintText: 'Add a thoughtful reply…', border: OutlineInputBorder()))), const SizedBox(width: 8), IconButton.filled(onPressed: _sending ? null : _send, icon: const Icon(Icons.send), tooltip: 'Post comment')]))]))));
  String _time(String? value) { final date = DateTime.tryParse(value ?? ''); if (date == null) return 'Now'; final diff = DateTime.now().difference(date); return diff.inMinutes < 1 ? 'Now' : diff.inHours < 1 ? '${diff.inMinutes}m' : diff.inDays < 1 ? '${diff.inHours}h' : '${diff.inDays}d'; }
}
