"""Initial PostgreSQL schema

Revision ID: 1718e0de5e5a
Revises: 9e3df1547bb5
Create Date: 2026-07-15 23:16:27.619816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1718e0de5e5a'
down_revision = '9e3df1547bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('friend_request_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('friend_request_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
