"""Add avatar/cover blob columns

Revision ID: 176e04493698
Revises: 20260724_add_user_profile_fields
Create Date: 2026-07-24 18:09:44.541981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '176e04493698'
down_revision = '20260724_add_user_profile_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('avatar_mime', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('cover_photo_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('cover_photo_mime', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cover_photo_mime')
        batch_op.drop_column('cover_photo_data')
        batch_op.drop_column('avatar_mime')
        batch_op.drop_column('avatar_data')

    # ### end Alembic commands ###
