"""Add profile fields

Revision ID: 90656ace73df
Revises: a703c9078ea9
Create Date: 2024-12-03 14:58:22.729126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90656ace73df'
down_revision = 'a703c9078ea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('picture', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('picture')
        batch_op.drop_column('location')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
