"""Added friend_request_id to notifications

Revision ID: 99687426ff1d
Revises: 7560e3e1d84a
Create Date: 2025-03-01 14:58:55.239981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99687426ff1d'
down_revision = '7560e3e1d84a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('friend_request_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_notifications_user_id", 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key("fk_notifications_friend_request", 'friend_requests', ['friend_request_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('friend_request_id')

    # ### end Alembic commands ###
