"""test

Revision ID: 9e3df1547bb5
Revises: e2f4a1c9b700
Create Date: 2026-07-15 18:44:04.417397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e3df1547bb5'
down_revision = 'e2f4a1c9b700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_index('unique_user_post_like')
        batch_op.create_unique_constraint('unique_user_post_like', ['user_id', 'post_id'])

    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_post_like', type_='unique')
        batch_op.create_index('unique_user_post_like', ['user_id', 'post_id'], unique=1)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
