"""Added read column to Notification

Revision ID: c76e495df85b
Revises: 3f66be9eefa3
Create Date: 2025-03-24 17:39:59.211145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c76e495df85b'
down_revision = '3f66be9eefa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_notification')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', sa.Boolean(), nullable=True))
        batch_op.alter_column('friend_request_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('friend_request_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('read')

    op.create_table('_alembic_tmp_notification',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.VARCHAR(length=255), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('friend_request_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['friend_request_id'], ['friend_requests.id'], name='fk_notifications_friend_request'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_notifications_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
